# Generated by Django 4.0.5 on 2022-07-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='username',
            new_name='name',
        ),
    ]
