# Generated by Django 4.0.5 on 2022-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_username_accountmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
