# Generated by Django 4.0.5 on 2022-07-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
